version: '3.7'

services:
  zksync-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
      - "8080:8080"
    command: bash -c "echo 'export FWD_REST_ENDPOINT='${FWD_REST_ENDPOINT} >> /etc/apache2/envvars; service apache2 start; node forwarder.js"
    env_file: .env

