version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  zksync-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    command:
      - node
      - forwarder.js
    env_file: .env

