version: '3.7'

services:
  zksync-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
      - "8080:8080"
    command: bash -c "service apache2 start; node forwarder.js"
    env_file: .env

