name: trigger gitlab job
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger Job
      uses: appleboy/gitlab-ci-action@master
      with:
        url: http://gitlab.openmakers.pl/patryk/zksync-forwarder
        token: 2ee34e4bcc5699feb9b585a533c62a
        project_id: 24
